# =========================================
# PRODUCTION PROFILE
# =========================================

server.port=${SERVER_PORT:8080}


# =========================================
# DATABASE
# =========================================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver


# =========================================
# JPA
# =========================================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# =========================================
# JWT
# =========================================

jwt.secret=${JWT_SECRET}
jwt.access-expiration=${JWT_ACCESS_EXPIRATION:900000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:2592000000}


# =========================================
# REDIS
# =========================================

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}


# =========================================
# LOGGING
# =========================================

logging.level.root=INFO
logging.level.org.example.jpaentityrelationships=INFO
logging.level.org.springframework.security=WARN


# =========================================
# ACTUATOR
# =========================================

management.endpoint.health.show-details=never